#!/bin/bash

echo 'Killing sslstrip and ettercap'
killall sslstrip #if you still get an error; port already in use
killall ettercap #run lsof -i and check which process is using that port

echo 'stopping ip forwarding'
#ip_forwarding stop
echo "0" > /proc/sys/net/ipv4/ip_forward

echo 'flushing ip tables'
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain

exit 0
